### ISSUE TITLE
adding bytes

### ISSUE THREAD

**Issue by bocianu** [KarolS/millfork#16]
When i'm trying to compile this:

```
word sum
void main() {
    sum = 246 + 18
}
```
i'm getting error:  "The constant 264 is too big".
But why? sum is declared as word.

If one of operands is bigger than 255 or if casted to word, it recognizes result type corectly. 
Is it expected behaviour?

**Comment by KarolS** [comment]
Yes, this is the expected behaviour.

The type of the left side doesn't matter. The type check goes as follows:

* `246` fits in a byte, therefore it's a byte
* `18` fits in a byte, therefore it's a byte
* `+` has two bytes on its sides, therefore the result of `246+18` is a byte
* the constant evaluator sees the overflow and informs you that something is wrong

You can get the same issue in C/C++, but the compiler won't warn you. For example, most 32- and 64-bit compilers will compile the following without any warning:

    long long sum = 0x8000'0000u + 0x8000'0000u;

to `long long sum = 0;`, even thought `0x1'0000'0000u` would fit in a `long long` just fine.

The difference is that Millfork does this at every integer size (there are no privileged "default" integer types like `int` in C) and doesn't let obvious overflows compile.

**Comment by bocianu** [comment]
Ok! thanks. So you can close this issue.

**Comment by KarolS** [comment]
I'll close it when I make the error message nicer. Right now the compiler simply throws an exception and immediately exits. It is ugly. I want it to report the error, point to the correct line and continue compiling to search for more errors.

**Comment by KarolS** [comment]
Error reporting has been improved as of 0.3.12, closing.
