### ISSUE TITLE
Build instructions ?

### ISSUE THREAD

**Issue by Nullious** [KarolS/millfork#2]
Could you post a tutorial on how to build Millfork ?
I'd love to get the latest goodies as there have been no new releases in a while :( 
I've never used scala or sbt before, I did try stumbling around but have had no luck ?
likely not due to millfork, likely I don't know what i'm doing and finding weird errors with jdk versions etc ? version numbers of the software used to build would help in this situation too. 

thanks

**Comment by KarolS** [comment]
So far, I was building it using sbt on JDK 1.8, and I had to hunt down and manually install some test dependencies, so building Millfork is not trivial. I also noticed today that it doesn't compile on Java 11, so I fixed it. There are still some issues with building Millfork with newer Javas, so still I recommend using 8.

I've just uploaded a short guide how to build Millfork with or without tests, please tell me later if it works for you: https://github.com/KarolS/millfork/blob/master/COMPILING.md

If it doesn't, then please wait few days, as I'm currently wrapping up some tiny annoying issues and I plan on releasing a new build within a week.

**Comment by Nullious** [comment]
This gave me a .jar file that compiled my CPC sample fine. I don't have my C64 stuff here with me I see no reason to believe there'll be a problem. 
thank for this. ( it was the src/test folder, and dependencies that I fell down a rabbit hole trying to solve )

**Comment by KarolS** [comment]
Glad to hear it.

The issue with the tests is that I couldn't find any CPU emulators in Maven Central (except for a Z80 emulator), and they are kinda necessary to check if the compiler actually works, so testing requires some manual downloading and installing. The compiler itself doesn't depend on anything weird.

I could redesign the project so that the compiler and the tests are separate SBT projects (and maybe even carve out a Scala.js version for an online demo?), but that's a lot of work, so I will probably never get around to do it.
