### ISSUE TITLE
VariableType `array` is not defined

### ISSUE THREAD

**Issue by ABlobOfGarbage** [KarolS/millfork#45]
i tried to compile the pong example for nes and i got this error message:
ERROR: (main.mfk:1259:29) VariableType `array` is not defined
       segment(chrrom) const array graphics @ $0000 = file("tiles.chr", 0)
why does this happen?
i didn't do any changes to the file.

**Comment by KarolS** [comment]
I'm guessing you're trying to compile the newest version of the pong example with the compiler version 0.3.14.

The examples are more or less designed to be compilable with the compiler compiled from sources at the same level, and the example was modified to showcase a new minor feature that will be a part of the next release, so it doesn't compile with 0.3.14.

You can compile the previous version of that example: https://github.com/KarolS/millfork/blob/b10c7321e5a5731b0e57cd03187ddcc8fbc7539f/examples/nes/pong.mfk
and in general, browse examples at https://github.com/KarolS/millfork/tree/v0.3.14 instead of master.

Sorry for the confusion, I'll do two things to prevent such problems in the future:

* I'll document that the examples are supposed to be compiled with a freshly compiled compiler and link to the examples compatible with the releases

* I'll fix the error message, as it is too confusing and it doesn't give a slightest clue to what might have gone wrong

**Comment by ABlobOfGarbage** [comment]
Thanks!
Everything works fine now (:
