### ISSUE TITLE
Non-constant array range bounds error with constants as array bounds

### ISSUE THREAD

**Issue by paulfnicholls** [KarolS/millfork#51]
Trying to compile the .mfk file in the attached zip file:
[constError.zip](https://github.com/KarolS/millfork/files/4943071/constError.zip)

gives the error below:

**C:\programming\c64\miniMIKEgit>"C:\utilities\millfork-0.3.16\millfork.exe" -t c64 ""C:\programming\c64\miniMIKEgit\constError.mfk""
ERROR: (constError.mfk:17:1) Array `levelData` has non-constant length
       array(byte) levelData[MAP_SIZE];
       ^
INFO:  Did you forget to import an appropriate module?
FATAL: Stack overflow levelData
Exception in thread "System-2" java.lang.AssertionError: Stack overflow levelData**

Here is the code from the attached file:
```
// room size in tiles (characters for now)
const byte ROOM_WIDTH      = 8;
const byte ROOM_HEIGHT     = 8;

const byte ROOM_SIZE       = ROOM_WIDTH * ROOM_HEIGHT;

// maximum room count in x & y directions
const byte LEVEL_SIZE_X      = 5;
const byte LEVEL_SIZE_Y      = 5;

// map size in tiles (characters for now)
const byte MAP_WIDTH       = ROOM_WIDTH  * LEVEL_SIZE_X;
const byte MAP_HEIGHT      = ROOM_HEIGHT * LEVEL_SIZE_Y;

const word MAP_SIZE        = MAP_WIDTH * MAP_HEIGHT;

array(byte) levelData[MAP_SIZE];

void main() {
  levelData[0] = 1;
}

```

**Comment by KarolS** [comment]
Thanks for the report!

The cause of this bug is dead code elimination. For some reason, array sizes did not count as uses, so constants used only as array sizes were considered dead code and therefore removed. 
I implemented the fix and it will be in the next release.

As a workaround, I recommend just using the constant literally anywhere else, so it's not considered unused.

**Comment by paulfnicholls** [comment]
Thanks for the quick fix and workaround in the meanwhile mate 👍
