### ISSUE TITLE
Allow semicolons at the end of statements.

### ISSUE THREAD

**Issue by cdoty** [KarolS/millfork#6]
Allowing the ending semicolon would easy the transition back and forth between C like languages.

**Comment by KarolS** [comment]
I think it could be done – not in the exact way C does it, but enough to make some copy-pasting work.

Why doesn't Millfork use semicolons for anything? Well, initially Millfork was designed for two things:
* do things well where C doesn't
* allow easy integration of inline assembly

Since capabilities of early Millfork and C were wildly different, back then copying code verbatim would rarely work even if ignoring semicolons and making other small syntactic tweaks, so end-of-statement semicolons were disallowed to discourage copying. Even now, many common things behave subtly different between Millfork and C, for example integer promotions, recursion, and so on.
Also, most assemblers use semicolons for comments. Since those two roles for the semicolon are quite distinct, I decided to not use it in any of those roles.

However, Millfork got more and more and C-inspired features to the point that more and more semicolon-less C code would work fine in Millfork. I was also mildly annoyed several times when I did some copy-pasting and didn't clean up semicolons before compiling, so I gave it a bit more thought and here's what I'm planning to do:
* semicolons will be allowed at the end of the line, optionally followed by a normal comment (this means that there will still be just one statement per line)
* however, semicolons will not be allowed inside expressions, before `{` and in few other places that wouldn't make sense
* inside `asm` statements and functions, semicolons will be allowed to function as comment markers, but the comment text will not be allowed to contain `{` or `}` (to not confuse text editors that detect matching braces)

I'm now thinking which parts of this feature (if any) should require a `#pragma semicolons` directive and whether some semicolon uses should emit a warning (if not by default, then maybe with `-Wsemicolons`).

What do you think?

**Comment by Nullious** [comment]
Allowing them inside asm blocks would be pretty useful tbh. or essentially treat them as a single line comment everywhere ?

**Comment by KarolS** [comment]
I don't think allowing semicolon comments outside of assembly is necessary, even if it is more uniform. People used to C might wonder why `x = 1; y = 2;` they copied doesn't work as expected. I think that such code should give an error with a clear explanation that Millfork disallows both semicolon comments and multiple statements per line in order to get the programmer to clarify which option they mean.

Semicolon-based comments also wouldn't be the first assembly-only syntactical feature. For example, `#pragma intel_syntax` enables Intel-style hex literals in assembly and assembly only.

And as for the whole code copying thing, I was also considering writing a C-to-Millfork converter that would at least give a starting point for the porting process, tailored to the C dialects used by CC65 and (Z)SDCC of course. It would be a much more long-term solution that just tweaking the syntax.

**Comment by Nullious** [comment]
that's a fair point, I'm mostly interested in it for Asm comments.

**Comment by KarolS** [comment]
0.3.10 has been released and contains the change.
