### ISSUE TITLE
O2 optimization moves load operations out of loops

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#95]
Whenever while loops rely on a changing value (perhaps only globals?) and optimization >= O2 is enabled, the loop becomes tightly rolled and omits the load instruction:

```
byte nmi_finished
byte output

void main() {
  nmi_finished = 0
  // Enable NMI
  ppu_ctrl = %10010000

  if (output > 0) {
    // Read output so it doesn't get optimized out
    output = 0
  }

  while (nmi_finished == 0) {}
  output = 1

  while (true) {}
}

void nmi() {
  nmi_finished = 1
}

void irq() {

}
```

Without enabling optimization, this runs as expected, but with O2, we get the following output:
```
;line:14:main.mfk
;     while (nmi_finished == 0) {}
    LDA nmi_finished
.wh__00002:
    BEQ .wh__00002
```

This will obviously spin forever.

**Comment by KarolS** [comment]
I cannot test it right now, but does making `nmi_finished` volatile fix it?

**Comment by JettMonstersGoBoom** [comment]
volatile is the solution I've used in these cases.

**Comment by agg23** [comment]
`volatile` does indeed fix it. However, I'm not sure that it should be required to be specified. It's not clear that the compiler will optimize out the access in the loop, and the variable is defined outside of the function scope and has known external modifiers. Unfortunately it probably is roughly the same complexity to show a warning in this scenario vs fixing it from optimizing it out.

**Comment by KarolS** [comment]
Scope is only a namespacing feature, it doesn't influence how the optimizer handles variables. Non-volatile global variables are assumed to not be modified concurrently, so that they can be optimized without having to copy them to locals manually. 

Apart from `volatile` (which might be overkill and should be used only for things like single-byte locks), there is also a macro called `memory_barrier()`. It is an instruction for the optimizer that forces it to assume that any variable could have changed and it will not optimize any variable reads or writes across the macro (it can still optimize it on each of the sides separately). So `while (nmi_finished == 0) { memory_barrier() }` also works, even without `volatile`.

I'll close it now, I think everything is clear now.
